/* Copyright © 2026 Infinitum Imagery LLC. All rights reserved. */
'use strict';
const hostedAccount=['infinitummasstexting.web.app','infinitummasstexting.firebaseapp.com','localhost','127.0.0.1'].includes(location.hostname);
if(!hostedAccount)location.replace('https://infinitummasstexting.web.app/'+(location.pathname.endsWith('/admin.html')?'admin.html':'account.html'));
const $=id=>document.getElementById(id);
let config,session=null,selectedUser=null,refreshPromise=null,latestAccess=null,enrollmentComplete=false;
const status=message=>{$('status').textContent=message;};
function display(){const signed=!!session;$('auth-panel').hidden=signed;$('complete-signup').hidden=signed;$('session-panel').hidden=!signed;if(signed)$('account-email').textContent=session.email;}
async function json(url,body,token){
 const response=await fetch(url,{method:body?'POST':'GET',cache:'no-store',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});
 let data;try{data=await response.json();}catch{throw new Error('Account service is not available yet. Please try again later.');}
 if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message??'Could not complete this request.');return data;
}
async function auth(method,body){config??=await json('/__/firebase/init.json');return json('https://identitytoolkit.googleapis.com/v1/accounts:'+method+'?key='+encodeURIComponent(config.apiKey),body);}
function save(){if(session)sessionStorage.setItem('infinitum-session',JSON.stringify(session));else sessionStorage.removeItem('infinitum-session');display();}
async function token(force=false){
 if(!session)throw new Error('Sign in first.');if(!force&&session.expires>Date.now())return session.idToken;
 if(!refreshPromise)refreshPromise=(async()=>{config??=await json('/__/firebase/init.json');const response=await fetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(config.apiKey),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:session.refreshToken})});const d=await response.json();if(!response.ok)throw new Error('Sign in again to continue.');session={...session,idToken:d.id_token,refreshToken:d.refresh_token,expires:Date.now()+3300000};save();return session.idToken;})().finally(()=>{refreshPromise=null;});
 return refreshPromise;
}
async function api(path,body){return json('/api'+path,body,await token());}
function profileData(){if(!$('profile-form').reportValidity())throw new Error('Complete the required account details and confirmations.');return {fullName:$('full-name').value,country:$('country').value,organization:$('organization').value,adultAuthorized:$('adult-authorized').checked,accepted:$('legal-accept').checked,version:'2026-09-20.2'};}
async function enrollmentStatus(){const e=await api('/enrollment');enrollmentComplete=e.complete;$('profile-panel').hidden=e.complete;$('save-profile').hidden=false;if(!e.complete&&e.profile){$('full-name').value=e.profile.fullName??'';$('country').value=e.profile.country??'';$('organization').value=e.profile.organization??'';}return e.complete;}
$('complete-signup').addEventListener('click',()=>$('auth-form').requestSubmit());
$('profile-form').addEventListener('submit',e=>{e.preventDefault();if(!session)return;action(async()=>{await api('/enrollment',profileData());await refresh();});});
async function refresh(){await token(true);if(!await enrollmentStatus()){status('Complete your account details and review the agreements below.');return;}const a=await api('/account');latestAccess=a;$('plan-status').textContent=a.limit===null?(a.plan==='complimentary'?'Complimentary · no app sending cap':'Unlimited · no app sending cap'):a.plan.toUpperCase()+' · '+a.remaining+' of '+a.limit+' credits available';$('usage-status').textContent=a.used+' used · '+a.reserved+' reserved. Resets '+new Date(a.resetsAt).toLocaleString()+' (midnight UTC).';$('admin-link').hidden=!a.admin;if($('admin-panel'))$('admin-panel').hidden=!a.admin;document.querySelectorAll('[data-checkout]').forEach(b=>{b.disabled=a.premium;});status(a.admin?'Owner access verified. Your account is complimentary.':'Account updated.');}
async function action(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(error){status(error.message);}finally{buttons.forEach(b=>b.disabled=false);document.querySelectorAll('[data-checkout]').forEach(b=>{b.disabled=latestAccess?.premium===true;});}}
$('create').addEventListener('change',()=>{$('profile-panel').hidden=!$('create').checked;$('sign-in').hidden=$('create').checked;$('save-profile').hidden=true;$('sign-in').textContent=$('create').checked?'Create free account':'Sign in';$('password').autocomplete=$('create').checked?'new-password':'current-password';});
$('auth-form').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const create=$('create').checked;const details=create?profileData():null;const email=$('email').value.trim(),password=$('password').value;$('password').value='';const d=await auth(create?'signUp':'signInWithPassword',{email,password,returnSecureToken:true});session={email:d.email??email,idToken:d.idToken,refreshToken:d.refreshToken,expires:Date.now()+3300000};save();if(create){$('profile-panel').hidden=false;$('save-profile').hidden=false;await api('/enrollment',details);await enrollmentStatus();await auth('sendOobCode',{requestType:'VERIFY_EMAIL',idToken:d.idToken});status('Verification email sent. Open its link, then choose Refresh account.');}else await refresh();});});
$('reset').addEventListener('click',()=>action(async()=>{const email=$('email').value.trim();if(!email)throw new Error('Enter your email address first.');try{await auth('sendOobCode',{requestType:'PASSWORD_RESET',email});}catch{}status('If that account exists, a password-reset email will arrive shortly.');}));
$('verify').addEventListener('click',()=>action(async()=>{await auth('sendOobCode',{requestType:'VERIFY_EMAIL',idToken:await token()});status('Verification email sent.');}));
$('refresh').addEventListener('click',()=>action(refresh));
$('sign-out').addEventListener('click',()=>{session=null;selectedUser=null;latestAccess=null;enrollmentComplete=false;save();$('profile-panel').hidden=!$('create').checked;$('sign-in').hidden=$('create').checked;$('save-profile').hidden=true;if($('admin-panel'))$('admin-panel').hidden=true;status('Signed out of this browser. Your Mac app session is separate.');});
function billingURL(value){const url=new URL(value);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw new Error('Unexpected checkout address.');return url.href;}
document.querySelectorAll('[data-checkout]').forEach(b=>b.addEventListener('click',()=>action(async()=>{const d=await api('/billing/checkout',{interval:b.dataset.checkout,tier:b.dataset.tier??'pro'});window.location.assign(billingURL(d.url));})));
$('portal').addEventListener('click',()=>action(async()=>{const d=await api('/billing/portal',{});window.location.assign(billingURL(d.url));}));
if($('search-form')){
 $('search-form').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const result=await api('/admin/users?email='+encodeURIComponent($('search-email').value.trim()));$('users').replaceChildren();$('grant-form').hidden=true;for(const user of result.users){const button=document.createElement('button');button.textContent=user.email+' · '+(user.verified===false?'Email not verified':user.grant?.enabled?'Complimentary grant':'No complimentary grant');button.addEventListener('click',()=>{selectedUser=user;$('grant-target').textContent='Account: '+user.email;$('grant-form').hidden=false;});$('users').append(button);}status(result.users.length?'Select an account to manage its access.':'No account found. Ask them to sign up and verify their email.');});});
 async function grant(enabled){if(!selectedUser)throw new Error('Select an account first.');const reason=$('grant-reason').value.trim();if(reason.length<3)throw new Error('Enter a reason for the audit log.');const date=$('grant-expiry').value;const expiresAt=date?new Date(date+'T23:59:59Z').getTime():null;await api('/admin/grant',{uid:selectedUser.uid,enabled,reason,expiresAt});status((enabled?'Unlimited app access granted to ':'Complimentary access revoked for ')+selectedUser.email+'. The change is recorded in the audit log.');}
 $('grant-form').addEventListener('submit',e=>{e.preventDefault();action(()=>grant(true));});$('revoke').addEventListener('click',()=>action(()=>grant(false)));
}
try{session=JSON.parse(sessionStorage.getItem('infinitum-session')??'null');}catch{session=null;}if(hostedAccount){display();if(session)action(refresh);}
